---
- name: install apche2, copy content in index.html and start apache2.
  become: true
  hosts: all
  tasks:
  - name: install apche2
    apt:
     name: apache2
     state: latest
  - name: copy content in index.html
    copy:
     content: "Welcome to Ansible Playbook with Handlers"
     dest: /var/www/html/index.html
    notify:
     - start apche2
  handlers:
  - name: start apache2
    service:
     name: apache2
     state: started
