---
- name: install apache2
  become: true
  hosts: all
  tasks:
  - name: install apache2
    apt:
     name: apache2
     state: latest
  - name: copy index.html
    copy:
     src: index.html
     dest: /var/www/html/index.html
  - name: start apache2
    service:
     name: apache2
     state: started
